- type: playTimeTracker
  id: JobSFRifleman

- type: playTimeTracker
  id: JobSFSeniorRifleman

- type: playTimeTracker
  id: JobSFEngineer

- type: playTimeTracker
  id: JobSFCorpsman

- type: playTimeTracker
  id: JobSFCommander

- type: playTimeTracker
  id: JobSFPilot
