- type: entity
  id: SpawnPointSolfedRifleman
  parent: SpawnPointJobBase
  name: Solfed Rifleman spawner
  components:
  - type: SpawnPoint
    job_id: SolfedRifleman
  - type: Sprite
    layers:
      - state: green
      - state: passenger

- type: entity
  id: SpawnPointSolfedSeniorRifleman
  parent: SpawnPointJobBase
  name: Solfed Senior Rifleman spawner
  components:
  - type: SpawnPoint
    job_id: SolfedSeniorRifleman
  - type: Sprite
    layers:
      - state: green
      - state: passenger

- type: entity
  id: SpawnPointSolfedEngineer
  parent: SpawnPointJobBase
  name: Solfed Engineer spawner
  components:
  - type: SpawnPoint
    job_id: SolfedEngineer
  - type: Sprite
    layers:
      - state: green
      - state: passenger

- type: entity
  id: SpawnPointSolfedCorpsman
  parent: SpawnPointJobBase
  name: Solfed Corpsman spawner
  components:
  - type: SpawnPoint
    job_id: SolfedCorpsman
  - type: Sprite
    layers:
      - state: green
      - state: passenger

- type: entity
  id: SpawnPointSolfedCommander
  parent: SpawnPointJobBase
  name: Solfed Commander spawner
  components:
  - type: SpawnPoint
    job_id: SolfedCommander
  - type: Sprite
    layers:
      - state: green
      - state: passenger

- type: entity
  id: SpawnPointSolfedPilot
  parent: SpawnPointJobBase
  name: Solfed Pilot spawner
  components:
  - type: SpawnPoint
    job_id: SolfedPilot
  - type: Sprite
    layers:
      - state: green
      - state: passenger

