- type: job
  id: SolfedEngineer
  name: Engineer
  description: Obey your orders, do your small part of big work.
  playTimeTracker: JobSFEngineer
  startingGear: SolfedEngineerGear
  icon: "JobIconEngineerSolfed"
  supervisors: job-supervisors-hos
  canBeAntag: false
  requirements:
  - !type:AgeRequirement # Minimum 18
    requiredAge: 18
  - !type:AgeRequirement # Maximum 45
    requiredAge: 45
    inverted: true
  - !type:SpeciesRequirement # Humans only
    species:
    - Human
  access:
  - Maintenance
  - External
  components:
  - type: RoleTicketCost
    ticketCost: 1
    deathMessage: "Solfed Engineer KIA. -1 ticket"

- type: startingGear
  id: SolfedEngineerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSolarGraySolfed
    id: DogtagSolfedEngineer
    ears: ClothingHeadsetAltSOLFED
    gloves: ClothingHandsGlovesCombatInsulated
    back: ClothingDuffelLoadouts
  storage:
    back:
    - BoxMRE
