- type: job
  id: SolfedRifleman
  name: Rifleman
  description: Obey your orders, do your small part of big work.
  playTimeTracker: JobSFRifleman
  startingGear: SolfedRiflemanGear
  icon: "JobIconRiflemanSolfed"
  supervisors: job-supervisors-hos
  canBeAntag: false
  requirements:
  - !type:AgeRequirement # Minimum 18
    requiredAge: 18
  - !type:AgeRequirement # Maximum 45
    requiredAge: 45
    inverted: true
  - !type:SpeciesRequirement
    species:
    - Human
    - Reptilian
    - Moth
  access:
  - Maintenance
  - External
  components:
  - type: RoleTicketCost
    ticketCost: 1
    deathMessage: "Solfed Rifleman KIA. -1 ticket"

- type: startingGear
  id: SolfedRiflemanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSolarGraySolfed
    id: DogtagSolfedRifleman
    ears: ClothingHeadsetAltSOLFED
  storage:
    back:
    - MultitoolUtility
  inhand:
  - PaperSolfedBucklete
