- type: job
  id: SyndyMedic
  name: Combat Medic
  description: Keep the team operational. A dead operative is a failed investment.
  playTimeTracker: JobSyndyMedic
  startingGear: SyndyMedicGear
  icon: "JobIconSyndyMedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  requirements:
  - !type:AgeRequirement # Minimum 18
    requiredAge: 18
  - !type:AgeRequirement # Maximum 45
    requiredAge: 45
    inverted: true
  - !type:SpeciesRequirement
    species:
    - Human
  access:
  - Maintenance
  - External
  components:
  - type: RoleTicketCost
    ticketCost: 1
    deathMessage: "Syndy Combat Medic KIA. -1 ticket"

- type: startingGear
  id: SyndyMedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    id: DogtagSyndyMedic
    ears: ClothingHeadsetAltSyndy
