
- type: loadoutGroup
  id: LoadoutSolfedEngineerSpecial
  name: loadout-group-vxs-special
  minLimit: 1
  maxLimit: 1
  loadouts:
  - C4BoxLoadout
  - ThermobaricHADGL

- type: loadoutGroup
  id: SpecialSyndyMarksman
  name: loadout-group-vxs-special
  minLimit: 0
  maxLimit: 1
  loadouts:
  - SpecialSyndyMarksmanLoadout
