- type: loadout
  id: HatSolarGray
  equipment:
    head: ClothingHeadHatSolarGray

- type: loadout
  id: HatSolarFASTHelmet
  equipment:
    head: ClothingHeadHelmetTacticalKevlar

- type: loadout
  id: HatMercHelmet
  equipment:
    head: ClothingHeadHelmetMerc
