- type: loadout
  id: NeckArmbandBlue
  equipment:
    neck: ClothingNeckArmbandBlue

- type: loadout
  id: NeckArmbandYellow
  equipment:
    neck: ClothingNeckArmbandYellow

- type: loadout
  id: NeckShoulderboardPVT
  equipment:
    neck: ShoulderboardSolfedPrivate

- type: loadout
  id: NeckShoulderboardPFC
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobSFRifleman
      time: 21600 # 6h
  equipment:
    neck: ShoulderboardSolfedEfreitor

- type: loadout
  id: NeckShoulderboardSGT
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobSFRifleman
      time: 360000 # 100h
  equipment:
    neck: ShoulderboardSolfedSergeant

- type: loadout
  id: NeckShoulderboardCPLPilot
  equipment:
    neck: ShoulderboardSolfedCapral

- type: loadout
  id: NeckShoulderboardSGTPilot
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobSFPilot
      time: 21600 # 6h
  equipment:
    neck: ShoulderboardSolfedSergeant

- type: loadout
  id: NeckShoulderboardSSGTPilot
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobSFPilot
      time: 360000 # 100h
  equipment:
    neck: ShoulderboardSolfedStarshina

- type: loadout
  id: NeckShoulderboardSSGTCommander
  equipment:
    neck: ShoulderboardSolfedStarshina

- type: loadout
  id: NeckShoulderboardLtColCommander
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobSFCommander
      time: 21600 # 6h
  equipment:
    neck: ShoulderboardSolfedLieutenantColonel

- type: loadout
  id: NeckShoulderboardColCommander
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobSFCommander
      time: 360000 # 100h
  equipment:
    neck: ShoulderboardSolfedColonel
